# Language info
language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "Nothing to install"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed achrafezzaam/udagram-api-feed:v1
  - docker tag udagram-api-user achrafezzaam/udagram-api-user:v1
  - docker tag udagram-frontend achrafezzaam/udagram-frontend:v1
  - docker tag udagram-reverseproxy achrafezzaam/udagram-reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD". | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push achrafezzaam/udagram-api-feed:v1
  - docker push achrafezzaam/udagram-api-user:v1
  - docker push achrafezzaam/udagram-frontend:v1
  - docker push achrafezzaam/udagram-reverseproxy:v1